### ISSUE TITLE
ImportError: cannot import name 'I2VGenXLPipeline' from 'diffusers' (E:\IMAGE\ComfyUI_test\python_embeded\Lib\site-packages\diffusers\__init__.py)

### ISSUE THREAD

**Issue by whmc76** [ZHO-ZHO-ZHO/ComfyUI-I2VGenXL#1]
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_test\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-I2VGenXL\__init__.py", line 1, in <module>
    from .I2VGenXL import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-I2VGenXL\I2VGenXL.py", line 9, in <module>
    from diffusers import I2VGenXLPipeline
ImportError: cannot import name 'I2VGenXLPipeline' from 'diffusers' (E:\IMAGE\ComfyUI_test\python_embeded\Lib\site-packages\diffusers\__init__.py)

**Comment by yiyan32** [comment]
please update your diffusers module to 0.26.1

**Comment by whmc76** [comment]
updated 0.26.2 good
