### ISSUE TITLE
opencv-python and accelerate are needed, but no in the requirements.txt

### ISSUE THREAD

**Issue by davyzhang** [ZHO-ZHO-ZHO/ComfyUI-I2VGenXL#2]
pip install opencv-python
pip install accelerate

**Comment by Kryptonic83** [comment]
seems so, I got this after running the simple workflow. I'll try installing accelerate.
```
Error occurred when executing I2VGenXL_ModelLoader_Zho:

`enable_model_cpu_offload` requires `accelerate v0.17.0` or higher.

File "H:\AI\pinokio\api\comfyui.git\app\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "H:\AI\pinokio\api\comfyui.git\app\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "H:\AI\pinokio\api\comfyui.git\app\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "H:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-I2VGenXL\I2VGenXL.py", line 38, in load_model
pipe.enable_model_cpu_offload()
File "H:\AI\pinokio\api\comfyui.git\app\env\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1432, in enable_model_cpu_offload
raise ImportError("`enable_model_cpu_offload` requires `accelerate v0.17.0` or higher.")
```

edit: yep, that worked.

**Comment by ffdown** [comment]
Traceback (most recent call last):
  File "E:\AI\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\ComfyUI\custom_nodes\ComfyUI-I2VGenXL\__init__.py", line 1, in <module>
    from .I2VGenXL import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\AI\ComfyUI\custom_nodes\ComfyUI-I2VGenXL\I2VGenXL.py", line 9, in <module>
    from diffusers import I2VGenXLPipeline
ImportError: cannot import name 'I2VGenXLPipeline' from 'diffusers' (C:\Users\user\AppData\Roaming\Python\Python310\site-packages\diffusers\__init__.py)

Cannot import E:\AI\ComfyUI\custom_nodes\ComfyUI-I2VGenXL module for custom nodes: cannot import name 'I2VGenXLPipeline' from 'diffusers' (C:\Users\user\AppData\Roaming\Python\Python310\site-packages\diffusers\__init__.py)
