### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by oktetopython** [ZHO-ZHO-ZHO/ComfyUI-I2VGenXL#3]
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-I2VGEN-XL\nodes.py", line 3, in <module>
    from modelscope.pipelines import pipeline
ModuleNotFoundError: No module named 'modelscope'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-I2VGEN-XL\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "H:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-I2VGEN-XL\nodes.py", line 7, in <module>
    from modelscope.pipelines import pipeline
ModuleNotFoundError: No module named 'modelscope'

Cannot import H:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-I2VGEN-XL module for custom nodes: No module named 'modelscope'

**Comment by aleksej622** [comment]
Same thing here

**Comment by aleksej622** [comment]
Did you manage to get it to work?

**Comment by camoody1** [comment]
Same error here...

```
Installing collected packages: modelscope
  Attempting uninstall: modelscope
    Found existing installation: modelscope 1.11.1
    Uninstalling modelscope-1.11.1:
      Successfully uninstalled modelscope-1.11.1
Successfully installed modelscope-1.13.1

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-I2VGEN-XL\nodes.py", line 3, in <module>
    from modelscope.pipelines import pipeline
ModuleNotFoundError: No module named 'modelscope'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-I2VGEN-XL\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-I2VGEN-XL\nodes.py", line 7, in <module>
    from modelscope.pipelines import pipeline
ModuleNotFoundError: No module named 'modelscope'

Cannot import H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-I2VGEN-XL module for custom nodes: No module named 'modelscope'
```
