### ISSUE TITLE
KeyError: 'class_type'

### ISSUE THREAD

**Issue by shirubei** [ZHO-ZHO-ZHO/ComfyUI-I2VGenXL#8]
感谢分享！
comfyui 里面加载了标注工作流后，点Queue Prompt的时候报错如下，请问该如何解决？
基础工作流没有问题。

Error handling request
Traceback (most recent call last):
  File "D:\Python310\stable\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python310\stable\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python310\stable\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python310\stable\ComfyUI\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python310\stable\ComfyUI\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python310\stable\ComfyUI\ComfyUI\execution.py", line 626, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
                                       ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'class_type'

[comfyui.log](https://github.com/ZHO-ZHO-ZHO/ComfyUI-I2VGenXL/files/14468559/comfyui.log)

**Comment by shirubei** [comment]
不知道跟下面这个是不是有关系，它说是 comfyui-art-venture 造成的，但我的环境里面没有安装 comfyui-art-venture
https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved/issues/133
